### ISSUE TITLE
The reliability of 1st moment X and Y positions

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#1275]
The S/N vs XPEAK-X1:

<img width="626" height="453" alt="Image" src="https://github.com/user-attachments/assets/ee6c3cdb-3817-41b3-b6a8-82bc82f19e8d" />

The S/B vs . XPEAK-X:

<img width="626" height="453" alt="Image" src="https://github.com/user-attachments/assets/f0ff1e59-5dc6-4061-bac2-da3900a49fa9" />

While the second plot looks good, the 1st one has two weird features:
1. The jump at around S/N ~15
2. The max difference is a bit larger than what we want idealy.

ToDo:
1. Understand what the origin of this jump is
2. We may want to consider limiting the steps / max mobility of the 1st moment estimation.

**Comment by agioffe** [comment]
Both features have a single cause, in `imUtil/+sources/+mex/moment1_cube.cpp`, and it reproduces to
the digit.

### ToDo 1: where the jump comes from

`imUtil.sources.moments` calls the mex with `MaxIter=8`, `SigmaWidth=[3 1.5]`,
`MaxStepSize=[0.1 0.1]`. Inside the iteration loop the step is **clamped first**, and the
convergence test is then applied to the *clamped* step:

```cpp
dxp = clampStep(dxp, maxStepThis);              // "Always clamp"
...
x0 += dxp;  dxOut = dxp;
...
if (it >= 1) {
    if (std::abs(dx) < tol && std::abs(dy) < tol) smallCount++;   // tol = sigma2 / SN
    else smallCount = 0;
    if (smallCount >= 2) { iterConv = it+1; break; }
}
```

So as soon as `tol > MaxStep`, i.e.

```
SN < SigmaWidth(2) / MaxStep = 1.5 / 0.1 = 15
```

*every* step passes the test by construction, `smallCount` reaches 2 at the third update, and the
routine reports convergence (`IterConv = 3`) while it is still travelling at full clamp speed. Total
travel is then 3 loop steps plus the final polishing step:

* `SN < 15` : 4 x 0.1 = **0.40 pix**
* `SN >= 15` : a railed source never satisfies the test, so it runs `MaxIter` = 8 steps plus the
  polish = 9 x 0.1 = **0.90 pix**

which are the two box heights in your first plot, and 15 is the jump.

### The controlled test

Same synthetic image every time; the only thing varied is the `SN` argument, which the mex uses
*solely* for `tol`:

| SN | 14.0 | 14.9 | **15.0** | 15.1 | 20 | 1000 |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| displacement | 0.4000 | 0.4000 | **0.8746** | 0.8746 | 0.8746 | 0.8746 |
| `IterConv` | 3 | 3 | **NaN** | NaN | NaN | NaN |

and the threshold can be moved twice, independently, exactly where predicted:

* `MaxStep` 0.1 -> 0.05 moves it to `SN` = 1.5/0.05 = **30** (envelopes 0.20 / 0.45)
* `SigmaWidth(2)` 1.5 -> 0.75 moves it to `SN` = 0.75/0.1 = **7.5** (`IterConv` 3 -> 4)

Since the synthetic test has no detection iterations at all, this also rules out the natural
alternative explanation - an iteration boundary of `multiIterExtractor` falling near that brightness.

### On real data: plot against `SN_2`, not `SN`

`find_measure_sources` passes `SN_W = Src.SN(:,2)`, i.e. the **`SN_2`** column, as the convergence
weight, whereas the plots above use the catalog `SN`, which is `SNm` from `psfPhotCube` - a
different quantity measured later. That is why the jump looks smeared rather than sharp. Against
`SN_2` it is a knife edge (20-epoch visit `LAST.01.08.03` 2023-06-16, 480 epoch catalogs, 300,492
unflagged sources):

| `SN_2` bin | 13-14 | 14.0-14.5 | 14.5-15.0 | 15.0-15.5 | 15.5-16 | 30-50 |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| max abs(XPEAK-X1) | 0.4000 | 0.4000 | **0.4000** | **0.9000** | 0.9000 | 0.9000 |

<img src="https://raw.githubusercontent.com/EranOfek/AstroPack/dev1/wiki_images/issue1275_moment_rails.png" alt="first-moment step rails" width="1000">

### The bigger problem is not the jump

**34.9% of all sources with `SN_2` < 15 have `XPEAK-X1` sitting at exactly +/-0.400** (within 0.001)
- 58,700 of 168,096. For those sources the first moment is not a measurement, it is the clamp. Above
the threshold only 0.14% rail at 0.900. Panel (c) shows the two spikes.

The consequence is a low-S/N astrometric bias, not just a cosmetic feature: a faint source whose
true centroid is more than 0.4 pix from `XPEAK` cannot reach it, so `X1` is systematically
compressed toward the integer pixel grid exactly where the centroid matters most.

### ToDo 2: the proposed remedy has the wrong sign

"Limiting the steps / max mobility" read literally means reducing `MaxStepSize`. But the threshold
is `SigmaWidth(2)/MaxStep`, so a *smaller* step **raises** the S/N below which sources are
spuriously frozen, i.e. it puts more sources into the bad regime - which is what the
`MaxStep` = 0.05 row above demonstrates (boundary 15 -> 30).

There are two separable defects and they want different fixes:

**A - the spurious convergence (the jump).** Test convergence on the **unclamped** step, or refuse
to count an iteration whose step was clamped. Roughly three lines in the `.cpp`. Note the
side-effect: with A alone, faint sources stop being frozen at 0.4 and become free to travel the
full 0.9, so low-S/N centroids get *more* mobile, not less. A on its own probably makes faint
astrometry worse.

**B - the +/-0.9 envelope (your point 2).** Total mobility is `(MaxIter+1) * MaxStep`. Capping it
needs a *cumulative*-displacement limit measured from the initial `XPEAK`, as a separate argument -
not a smaller per-iteration step. With A fixed and B set to ~0.5 pix the envelope would become
+/-0.5 at all S/N, matching what the PSF-fit position already does in your second plot.

I have the synthetic harness and the reduced visit set up, so I can implement and verify either or
both - say which, and what value you want for the cumulative cap. One small thing that would help
verification: the mex already returns `IterConv`, but it is not propagated to the catalog; carrying
it (or just a "centroid railed" flag) would make this directly checkable in production data.

**Comment by EranOfek** [comment]
Try to understand what is the nature of the 0.4 and 0.9 limits - why are there two of them, and I think it should be 0.5?

**Comment by agioffe** [comment]
### Why two limits, and why neither is 0.5

Neither number is physical; both are "number of updates × `MaxStep`". Every update is clamped to `MaxStep` = 0.1 per axis, so a source whose centroid is farther than that from `XPEAK` moves by exactly 0.1 per update until the routine stops, and it stops in one of two ways:

| regime | why it stops | updates | travel |
| :-- | :-- | :-- | :-- |
| `SN_2` < 15 | spurious convergence: `tol = 1.5/SN > 0.1`, so the *clamped* step always passes; `smallCount` reaches 2 on loop iteration 3 | 3 in the loop + 1 unconditional "polish" | **0.40** |
| `SN_2` ≥ 15 | never converges, exhausts `MaxIter` = 8 | 8 + 1 polish | **0.90** |

General form `MaxStep1 + N·MaxStep`, verified on the mex: `MaxIter` 4/6/8/12 → 0.5/0.7/0.9/1.3 above the threshold and 0.40 regardless of `MaxIter` below it; `MaxStepSize = [0.3 0.1]` → 0.6. The clamp is per axis, so the radial envelope is √2 larger (0.57 / 1.27). None of these constants knows about the pixel.

On 0.5: that is the half-pixel bound for a *correct* peak pixel, but `XPEAK` is the maximum of the matched-filtered *noisy* image. In a simulated field (Gaussian PSF σ = 1.57 px ≙ FWHM 3.7, B = 191 e⁻, RN = 3, detected and measured with `find_measure_sources` exactly as in production, 4,692 matched sources), the true centroid is more than 0.5 px from `XPEAK` for **15 % of sources at `SN_2` 10–15, 24 % at 7–10, 36 % at 5–7** (still 2–5 % at `SN_2` > 30). A hard cap of 0.5 from `XPEAK` would clip real measurements at low S/N. With the weighting fixed as below, no cap is needed — it never bites.

### The actual defect: since #701, `X1` is a plain centroid in a 3.75-px disc

`imUtil.sources.moments` subtracts the annulus background from the cube and then calls the mex with **`Back = 0`**. The mex weight is `w = I·g/(B + A·g)`; with `B = 0` the Gaussian window cancels exactly, `w = I/A`, and `X1` is the plain centroid of the pixels inside the fixed support disc `R = TruncateSigma·SigmaWidth(2) = 2.5·1.5 = 3.75 px`. Checked to 6 digits: with `Back = 0` and `k·σ₂` held at 6 px, sweeping σ₂ over 0.5–3 changes nothing, and the result equals a one-line MATLAB disc centroid. (The help of `moments` says `TruncateSigma` defaults to 3; the `arguments` block says 2.5 — the replay of the production cube only matches the catalog with 2.5, so 2.5 is what runs.)

So nothing regularises `X1` at low S/N except the 0.1 clamp, and the disc is too small for bright stars. Both effects are in the data. This visit re-reduced with current `dev1` (480 epoch catalogs, 300,489 unflagged sources):

1. **Bright stars are compressed toward `XPEAK` by ~18 %.** A plain centroid in a disc centred on `XPEAK` loses the far wing of an off-centre source. Noise-free: recovered/true offset = 0.82 for R = 3.75, 0.94 for 4.5, 0.99 for 6, independent of flux. Real data, `SN_2` > 100: slope of `X1−XPEAK` against the PSF-fit `X−XPEAK` = 0.82–0.87; the `X1−XPEAK` distribution of bright stars ends at ±0.42 while the PSF fit's ends at ±0.49. A sub-pixel-phase-dependent bias of up to ~0.09 px on the best-measured sources.
2. **Faint stars sit on the clamp.** 35.1 % of unflagged sources with `SN_2` < 15 (19.8 % of all) have `|X1−XPEAK|` = 0.400 exactly.

Neither exists in the catalogs of the same visit reduced on 2026-04-12, two days before ba4701283 (#701, 2026-04-14) replaced `imUtil.image.moment2` with `imUtil.sources.moments` + the mex: there the bright-star slope is 0.97–0.99 and there are no rails. So both are a regression from #701, not a property of first moments.

For the record, the mex's *documented* contract (cube including the background, `Back` = its level) is worse still: the sky in the numerator pulls the estimate toward the starting point, slope 0.04–0.3 up to `SN_2` 30 in the simulation. The header describes a weighting the code does not implement for either calling convention.

### What works

Same mex, three changes, tested as a scratch build (extra arguments `ConvOnRaw`, `MaxCumul`, `BsCube`; nothing in the tree touched):

- pass the annulus-subtracted cube **and** the variance level (`AnnulusStd²`, already computed in `moments`) as `Back`, and estimate `A` from the subtracted cube — `w = I_sub·g/(V + A·g)`, i.e. signal × PSF / variance;
- `TruncateSigma` = 4 (R = 6 px) — with proper weights the wider support costs nothing at low S/N and removes the compression;
- test convergence on the **unclamped** step, but keep the 0.1 per-step clamp: with no clamp at all the faintest bin blows up (rms 1.25 px on real stamps).

Simulation — rms of `X1 − X_true` (x,y pooled), fraction of the true sub-pixel offset recovered ("slope"), and fraction railed:

| `SN_2` | 5–7 | 7–10 | 10–15 | 15–20 | 20–30 | 30–50 | 50–100 | >100 |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| rms, current | 0.496 | 0.342 | 0.241 | 0.178 | 0.134 | 0.091 | 0.071 | 0.056 |
| rms, current + raw-step convergence only | 0.519 | 0.357 | 0.245 | 0.178 | 0.134 | 0.091 | 0.071 | 0.056 |
| rms, current + raw-step + cap 0.5 | 0.501 | 0.346 | 0.243 | 0.177 | 0.133 | 0.091 | 0.071 | 0.056 |
| **rms, weighted, R = 6, raw-step** | **0.450** | **0.297** | **0.207** | **0.148** | **0.099** | **0.067** | **0.042** | **0.018** |
| rms, `psfPhotCube` with the true PSF | 0.484 | 0.314 | 0.221 | 0.157 | 0.108 | 0.075 | 0.047 | 0.022 |
| slope, current → weighted | 0.21 → 0.25 | 0.37 → 0.43 | 0.51 → 0.63 | 0.66 → 0.77 | 0.72 → 0.87 | 0.79 → 0.94 | 0.80 → 0.97 | 0.82 → 1.00 |
| railed, current → weighted | 27 % → 3 % | 24 % → 0 | 14 % → 0 | 1 % → 0 | 0 | 0 | 0 | 0 |

Fixing only the convergence test, with or without a cumulative cap, changes nothing beyond ±0.02: the clamp was acting as a shrinkage prior on an unweighted estimator, and lifting it trades bias for variance. The weighted estimator is better than the current one at every S/N and marginally better than the PSF fit in this Gaussian-PSF simulation.

Real stamps (one calibrated frame of this visit, 6,823 sources, reference = `psfPhotCube` with the empirical coadd PSF), rms of `X1 − X_psf`:

| `SN_2` | 5–7 | 7–10 | 10–15 | 15–20 | 20–30 | 30–50 | 50–100 | 100–300 |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| current | 0.403 | 0.322 | 0.252 | 0.206 | 0.158 | 0.150 | 0.106 | 0.091 |
| weighted, R = 6, raw-step | 0.247 | 0.183 | 0.139 | 0.105 | 0.092 | 0.091 | 0.076 | 0.073 |

and the bright-star slope against the PSF fit goes from 0.87 to 1.01.

The plot from the issue, redone on the central 3400×3400 px of all 20 frames (139,429 sources), the same stamps through the three estimators:

<img src="https://raw.githubusercontent.com/EranOfek/AstroPack/dev1/wiki_images/issue1275_weighted_vs_current.png" alt="SN_2 vs XPEAK-X1: current, weighted, PSF fit" width="1000">

(a) is the current `dev1`: the ±0.40 block below `SN_2` = 15 (34.9 % of those sources sit exactly on it) and the ±0.90 fan above. (b) is the weighted estimator: the envelope is ±0.5 at every S/N above ~10, 3.4 % of the `SN_2` < 15 sources still touch the 0.4 clamp (the very faintest), the bright-star 95th percentile is 0.478 instead of 0.431. (c) is the PSF fit for reference (its own faint ridge at +0.2 is `psfPhotCube`'s `MaxStep`, a separate matter).

### Proposal

1. `imUtil.sources.moments`: pass `AnnulusStd.^2` (or `Var` at `XPEAK`) instead of `B0 = 0`; `TruncateSigma` = 4; align the help with the `arguments` block.
2. `moment1_cube.cpp`: estimate `A` from the cube as given (already background-subtracted) and test convergence on the unclamped step; fix the header to describe the actual weighting. The per-step clamp stays; `MaxIter`, `MaxStep` and the polish then no longer set any envelope because the estimator no longer walks. (Carrying `M1.Iter` into the catalog would make this checkable in production.)

**Bottom line:** the jump and the 0.4/0.9 envelopes are pure clamp arithmetic (4 and 9 updates × 0.1) and a 0.5 cap is the wrong knob; the root cause is that since #701 `X1` is an unweighted centroid in a 3.75-px disc (`Back = 0` cancels the Gaussian window), which compresses bright-star positions by 18 % and leaves faint ones on the clamp. Restoring the weighting removes the rails and matches or beats the PSF fit at every S/N.

Not solved yet: nothing in the tree is changed, production still rails 20 % of all sources and compresses bright centroids. I can turn the above into a PR (with the `moments` unit test extended by the synthetic field); the closing evidence would be panel (b) reproduced from a production reduction. @EranOfek , should we implement 1 and 2?

**Comment by agioffe** [comment]
Same test on four more visits (20 frames each, central 3400×3400 px, all frames calibrated with the camera's master dark/flat from marvin, PSF = the visit's crop-13 coadd PSF from euclid), chosen for variety:

| visit | mount/cam | field | b | PSF FWHM | sky [e⁻] | sources/frame |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| 2025-07-25 21:14 | 02 / 02 | 1529 | −7° (dense) | 4.08 px | 133 | 24,600 |
| 2025-08-04 17:25 | 10 / 04 | 1677 | +42° | 4.55 px | 865 (bright sky) | 3,900 |
| 2025-09-20 23:02 | 05 / 03 | 904 | −47° (sparse) | 3.45 px | 154 | 2,100 |
| 2025-10-02 23:30 | 09 / 01 | 1171 | −17° | 3.44 px | 125 | 4,800 |

Since there is no truth on real data, the metric is **repeatability**: each star seen in ≥15 of the 20 frames, per-frame 6-parameter alignment from `SN_2` > 50 stars, then the std of each estimator's position across frames (single-frame std, x and y pooled), binned by the star's median `SN_2`:

| repeatability std [pix] | `SN_2` 5–7 | 7–10 | 10–15 | 15–30 | 30–100 | >100 |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| **dense −7°** current | 0.398 | 0.329 | 0.246 | 0.164 | 0.097 | 0.064 |
| weighted, R = 6, σ₂ = 1.5 | **0.365** | **0.302** | **0.222** | **0.147** | **0.082** | **0.043** |
| PSF fit | 0.493 | 0.416 | 0.318 | 0.214 | 0.133 | 0.080 |
| **sparse −47°** current | 0.436 | 0.363 | 0.262 | 0.171 | 0.084 | 0.047 |
| weighted, R = 6, σ₂ = 1.5 | **0.330** | **0.264** | **0.172** | **0.104** | **0.053** | **0.033** |
| PSF fit | 0.374 | 0.321 | 0.202 | 0.121 | 0.062 | 0.045 |
| **−17°** current | 0.420 | 0.343 | 0.247 | 0.167 | 0.086 | 0.052 |
| weighted, R = 6, σ₂ = 1.5 | **0.301** | **0.236** | **0.168** | **0.105** | **0.058** | **0.036** |
| PSF fit | 0.286 | 0.219 | 0.166 | 0.097 | 0.055 | 0.037 |
| **bright sky +42°** current | 0.418 | 0.419 | 0.380 | 0.352 | 0.277 | 0.253 |
| weighted, R = 6, σ₂ = 1.5 | **0.334** | **0.303** | **0.273** | 0.265 | 0.257 | 0.252 |
| PSF fit | 0.394 | 0.343 | 0.305 | 0.287 | 0.267 | 0.256 |

(The bright-sky visit has a 0.25-px alignment floor common to all three estimators — the frames do not map onto each other affinely to better than that — so only its low-S/N bins are informative.) The weighted moment is the most repeatable estimator in every bin of every visit, including bright stars, where it beats `psfPhotCube` by 20–45 %. Bright-star slope against the PSF fit 0.92–0.99 (current 0.69–0.88); fraction of `SN_2` < 15 sources on the 0.4 rail 35–51 % → 2–4 %.

Parameter grid (R = k·σ₂ with k = 3/4/5, σ₂ = 1.0/1.2/1.5/2.0, variance from `AnnulusStd²` vs the `Var` image at `XPEAK`, per-step clamp vs cumulative cap 0.7, `MaxIter` 8 vs 12) — what it changed:

- **k = 4 (R = 6 px)** confirmed: k = 3 and 5 are identical to ±0.002; k = 2.5 keeps the compression.
- **σ₂ = 1.5 (unchanged)**: 1.2 is 6 % better in the two FWHM-3.4 visits and 10 % worse in the dense FWHM-4.1 field; 1.0 and 2.0 are worse. Not worth changing.
- `AnnulusStd²` vs `Var(XPEAK)`: identical — use the annulus, it is already computed in `moments`.
- clamp 0.1 vs no clamp + cap 0.7, `MaxIter` 8 vs 12: identical repeatability. Keep the defaults.
- **One refinement to the convergence test**: with the raw step compared to `tol = σ₂/SN` alone, faint sources (`tol` = 0.25 at `SN_2` = 6) still stop after 3 clamped steps of 0.1 whenever the raw step is 0.1–0.25 (4–10 % on the 0.4 rail). Comparing the raw step to `min(σ₂/SN, MaxStep)` — a step that had to be clamped is never "converged" — brings it to 2–4 %, the remainder being sources that walk the full 0.9 (a neighbour inside the 6-px disc), which the existing `MaxIter·MaxStep` bound is the right place to stop.

So the proposal stands as written, with the tolerance changed to `min(SigmaWidth(2)/SN, MaxStep)`: `moments` passes `AnnulusStd.^2` as `Back` and `TruncateSigma` = 4; the mex takes `A` from the subtracted cube and tests the unclamped step against that tolerance. `SigmaWidth`, `MaxStepSize` and `MaxIter` stay at their current values.

**Comment by EranOfek** [comment]
I don't understand the fix, but do you mean that the suggested algorithm will make it like the middle plot?
This looks reasonable and much better than the current situation.
If this is the case, then go ahead. Looks fine to me.

**Comment by agioffe** [comment]
Yes, exactly. I tried on several visits from different fields and the plots look like the middle plot. I will push it and close.

**Comment by agioffe** [comment]
Pushed as f32df5002 on `dev1`:

- `imUtil.sources.mex.moment1_cube`: the second argument is now the per-slice noise variance level (the cube is background-subtracted; `A` is summed from the cube as given), weights `I·g/(Var + A·g)`; convergence is tested on the proposed (unclamped) step against `min(SigmaWidth(2)/SN, MaxStep)`. Header and help updated, `.mexa64` rebuilt.
- `imUtil.sources.moments`: passes `AnnulusStd.^2` (0 where not finite) instead of zeros; `TruncateSigma` = 4; help aligned with the code.
- `imUtil.sources.unitTest`: noise-free checks for the bright-star compression and the faint-source rail.

`SigmaWidth`, `MaxStepSize`, `MaxIter` unchanged. The in-tree build is bit-identical to the scratch variant tested above.

**Closing evidence** — the same visit reduced twice through `PipelineDemon` (local mode), 480 epoch catalogs each, before (63d66ef89) and after (f32df5002):

<img src="https://raw.githubusercontent.com/EranOfek/AstroPack/dev1/wiki_images/issue1275_production_before_after.png" alt="production SN_2 vs XPEAK-X1 before/after" width="900">

The rails are gone (sources at exactly 0.400: 35.1 % → 0.3 % of `SN_2` < 15; at 0.900: 0.06 % → 0.5 %, the latter being the `MaxIter·MaxStep` bound on sources that walk to a neighbour). The bright-star envelope is ±0.50 (95th percentile 0.502, was 0.424 — the compression is gone).

The low-S/N spread in the "after" panel is wider than in panel (b) of the frame-level test above (95th percentile 0.65 vs 0.47 at `SN_2` < 15). That is `XPEAK`, not `X1`: in production the peak comes from the empirical-PSF / multi-template detection of `multiIterExtractor` and is a poorer anchor than the σ = 1.5 Gaussian peak of the frame-level test (11 % of *bright* stars have the PSF-fit position > 0.5 px from `XPEAK` in production, vs 3 % there). `XPEAK − X1` is not the estimator's error. The estimator's error is what repeatability measures — the same 4,000 stars matched across the 20 epochs of the production catalogs, per-crop affine alignment, std of the position across epochs:

| repeatability std [pix] | `SN_2` 5–7 | 7–10 | 10–15 | 15–30 | 30–100 | >100 |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| `X1` before | 0.418 | 0.338 | 0.252 | 0.178 | 0.109 | 0.079 |
| **`X1` after** | **0.367** | **0.284** | **0.205** | **0.134** | **0.080** | **0.053** |
| `X` (PSF fit, production, for reference) | 0.351 | 0.259 | 0.185 | 0.120 | 0.074 | 0.050 |

`X1` improved in every bin, by 12–33 %, and now matches the production PSF fit (which is initialised at `X1` and uses the empirical PSF) to within ~5 %. Closing.
